// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompleteTask(arg1:number):Promise<void>;

export function CreateReward(arg1:string,arg2:number,arg3:string):Promise<main.Reward>;

export function CreateTask(arg1:string,arg2:string,arg3:Array<main.Reward>):Promise<main.Commission>;

export function DeleteReward(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetAvailableRewards():Promise<Array<main.Reward>>;

export function GetLocale():Promise<string>;

export function IsDev():Promise<boolean>;

export function LoadCommissions(arg1:number):Promise<Array<main.Commission>>;

export function MarkTodayAsClaimed():Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;
