// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompleteTask(arg1:number):Promise<void>;

export function CreateTask(arg1:string,arg2:string):Promise<main.Commission>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetLocale():Promise<string>;

export function IsDev():Promise<boolean>;

export function LoadCommissions(arg1:number):Promise<Array<main.Commission>>;
