// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTask(arg1) {
  return window['go']['main']['App']['CompleteTask'](arg1);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetLocale() {
  return window['go']['main']['App']['GetLocale']();
}

export function IsDev() {
  return window['go']['main']['App']['IsDev']();
}

export function LoadCommissions(arg1) {
  return window['go']['main']['App']['LoadCommissions'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}
