// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {main} from '../models';

export function ClaimCommissionForToday(arg1:number):Promise<void>;

export function ClaimDailyBonusForToday():Promise<void>;

export function ClearTodaysClaims():Promise<void>;

export function IsCommissionClaimed(arg1:number,arg2:time.Time):Promise<boolean>;

export function IsTodaysBonusClaimed():Promise<boolean>;

export function SetupClaimsForToday():Promise<Array<main.Reward>>;
