// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClaimCommissionForToday(arg1) {
  return window['go']['main']['ClaimsService']['ClaimCommissionForToday'](arg1);
}

export function ClaimDailyBonusForToday() {
  return window['go']['main']['ClaimsService']['ClaimDailyBonusForToday']();
}

export function IsCommissionClaimed(arg1, arg2) {
  return window['go']['main']['ClaimsService']['IsCommissionClaimed'](arg1, arg2);
}

export function IsTodaysBonusClaimed() {
  return window['go']['main']['ClaimsService']['IsTodaysBonusClaimed']();
}

export function SetupClaimsForToday() {
  return window['go']['main']['ClaimsService']['SetupClaimsForToday']();
}
