// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function CreateNewCommission(arg1:string,arg2:string,arg3:Array<main.Reward>):Promise<main.Commission>;

export function DeleteCommission(arg1:number):Promise<void>;

export function LoadCommissionsForDate(arg1:time.Time):Promise<Array<main.Commission>>;
