// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRealm(arg1) {
  return window['go']['main']['CommissionService']['AddRealm'](arg1);
}

export function AddRealms(arg1) {
  return window['go']['main']['CommissionService']['AddRealms'](arg1);
}

export function CreateNewCommission(arg1, arg2, arg3) {
  return window['go']['main']['CommissionService']['CreateNewCommission'](arg1, arg2, arg3);
}

export function DeleteCommission(arg1) {
  return window['go']['main']['CommissionService']['DeleteCommission'](arg1);
}

export function DeleteRealm(arg1) {
  return window['go']['main']['CommissionService']['DeleteRealm'](arg1);
}

export function GetAvailableRealms() {
  return window['go']['main']['CommissionService']['GetAvailableRealms']();
}

export function LoadCommissionsForDate(arg1) {
  return window['go']['main']['CommissionService']['LoadCommissionsForDate'](arg1);
}
