// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateReward(arg1) {
  return window['go']['main']['RewardService']['CreateReward'](arg1);
}

export function DeleteReward(arg1) {
  return window['go']['main']['RewardService']['DeleteReward'](arg1);
}

export function GetAvailableRewards() {
  return window['go']['main']['RewardService']['GetAvailableRewards']();
}

export function GetReward(arg1) {
  return window['go']['main']['RewardService']['GetReward'](arg1);
}

export function GetRewardIdsFromRewards(arg1) {
  return window['go']['main']['RewardService']['GetRewardIdsFromRewards'](arg1);
}

export function GetRewardsFromIds(arg1) {
  return window['go']['main']['RewardService']['GetRewardsFromIds'](arg1);
}

export function GetRewardsFromRewardsString(arg1) {
  return window['go']['main']['RewardService']['GetRewardsFromRewardsString'](arg1);
}
